### ISSUE TITLE
Blue Alba logo should be above copyright text in page footer

### ISSUE THREAD

**Issue by panchilo** [bluealba/website#5]

**Comment by mariavic** [comment]
footer{
	color: #fff;
	width: 100%;
	flex-direction: column;
	text-align: center;
	background: $BAprimary-color;
	a img{
		cursor: pointer;
		user-select: none;
		width: 35px;
		user-select: none;
		margin-top: 25px;
		padding: 0 5px;
		opacity: .8;
		transition: all .3s ease;
		&:hover{
			opacity: 1;
		}
	}
	p{
		font-size: 12px;
		font-weight: 300;
		margin: 10px 0 20px;
	}
}
