### ISSUE TITLE
Blue Alba to provide text for Contact Section

### ISSUE THREAD

**Issue by panchilo** [bluealba/website#6]

**Comment by panchilo** [comment]
Here it goes:

> At Blue Alba we combine our extensive experience in financial industry software development with our knowledge of the latest and greatest technologies to deliver the best solutions at all stages of the development lifecycle.
Thanks to our lean approach and agile processes you get the best return for your investment, avoiding unnecessary overhead without sacrificing quality.

> Our state-of-the-art architectural approach leverages the latest tendencies and tools in the software industry to guarantee your systems are secure, maintainable and robust.

> Our goal is to bring financial industry to the vanguard of software, while understanding the demanding and sensitive environment it operates in.

**Comment by panchilo** [comment]
@mariavic please change About Section using provided text

**Comment by mariavic** [comment]
<div class="s-left">
	<h3>About</h3>
	<div class="content">
		<p>At Blue Alba we combine our extensive experience in financial industry software development with our knowledge of the latest and greatest technologies to deliver the best solutions at all stages of the development lifecycle.</p>
		<p>Thanks to our lean approach and agile processes you get the best return for your investment, avoiding unnecessary overhead without sacrificing quality.</p>
		<p>Our state-of-the-art architectural approach leverages the latest tendencies and tools in the software industry to guarantee your systems are secure, maintainable and robust.</p>
		<p>Our goal is to bring financial industry to the vanguard of software, while understanding the demanding and sensitive environment it operates in.</p>
	</div>	
</div>

**Comment by mariavic** [comment]
s-left{
	width: 50%;
	.content{
		p{
			font-size: 18px;
			line-height: 24px;
			font-weight: 300;
			color: $BAprimary-color;
			margin-bottom: 20px;
			display: inline-block;
		}
		:first-child{
			margin-bottom: 0;
		}
	}
}

**Comment by panchilo** [comment]
Don't comment the code here. Code will be in the repo :-)
